### PR TITLE
feat: set the HOME environment variable before invoking a command

### PR DESCRIPTION
**Pull request by etorreborre**
This should solve #26 where the global `.gitignore` file cannot be found.

### CODE REVIEW

**Review by chshersh — CHANGES_REQUESTED** [review]
Looks great! Thanks for your contribution 💯 

Two things left:

- [ ] Could you add a changelog
- [ ] The `HOME` code here can be simplified
    - https://github.com/chshersh/zbg/blob/311e0351b555c9015a98c391a3ca7861c4fb6c35/lib/git.ml#L22-L27

**Comment by etorreborre** [comment]
- [x] Could you add a changelog
- [x] The HOME code here can be simplified -> Ah, yes of course!

**Review by chshersh — APPROVED** [review]
Awesome, looks great!

**Comment by etorreborre** [comment]
BTW I forgot to mention that this PR indeed solves #26
Before:
image
After:
image

**Review by chshersh — APPROVED** [review]
Thanks again!

**Pull request merged**
